In [3]:
from edgar import Company, set_identity

set_identity("Kedar Haldar kedar.haldar11@gmail.com")

In [4]:
apple = Company("AAPL")
apple

╭───────────────────────────────────────────────────────────────────────────────────╮
│ Apple Inc.  AAPL                                                                  │
│ 0000320193 • Nasdaq • Large Accelerated Filer                                     │
│                                                                                   │
│   Industry          3571: Electronic Computers                                    │
│   Fiscal Year       Sep 26                                                        │
│   Incorporated      California                                                    │
│   Phone             (408) 996-1010                                                │
│   Address           ONE APPLE PARK WAY, CUPERTINO, CA 95014                       │
╰────────────────────────────────── SEC Entity Data • company.docs for usage guide ─╯

In [5]:
financials = apple.get_financials()

income = financials.income_statement()
balance = financials.balance_sheet()
cashflow = financials.cash_flow_statement()

In [6]:
income

                                  APPLE INC.   AAPL
                                  CONSOLIDATED STATEMENT OF INCOME
                                  Sep 30, 2023 to Sep 27, 2025

                                                       Sep 27, 2025   Sep 28, 2024   Sep 30, 2023
   ───────────────────────────────────────────────────────────────────────────────────────────────
            Net sales:                                     $416,161       $391,035       $383,285
            Products                                       $307,003       $294,866       $298,085
            Services                                       $109,158        $96,169        $85,200
            Cost of sales:                                 $220,960       $210,352       $214,137
            Products                                       $194,116       $185,233       $189,282
            Services                                        $26,844        $25,119        $24,855
          Gross margin                                     $195,201       $180,683       $169,148
        Operating expenses:
              Research and development:                     $34,550        $31,370        $29,915
              Selling, general and administrative           $27,601        $26,097        $24,932
              Total operating expenses                      $62,151        $57,467        $54,847
            Operating income:                              $133,050       $123,216       $114,301
            Other income/(expense), net                      $(321)           $269         $(565)
          Income before provision for income taxes         $132,729       $123,485       $113,736
          Provision for income taxes                        $20,719        $29,749        $16,741
          Net income:                                      $112,010        $93,736        $96,995
        Earnings per share:
            Basic (in dollars per share)                       7.49           6.11           6.16
            Diluted (in dollars per share)                     7.46           6.08           6.13
        Shares used in computing earnings per share:
            Basic (in shares)                            14,948,500     15,343,783     15,744,231
            Diluted (in shares)                          15,004,697     15,408,095     15,812,547

   Source: SEC XBRL  •  (In millions, except shares in thousands and per share data)

In [7]:
balance

                                           APPLE INC.   AAPL
                                           CONSOLIDATED BALANCE SHEETS
                                           Sep 28, 2024 to Sep 27, 2025

                                                                                    Sep 27, 2025   Sep 28, 2024
   ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ASSETS:
      Current assets:
            Cash and cash equivalents:                                                   $35,934        $29,943
            Marketable securities:                                                       $18,763        $35,228
            Accounts receivable, net                                                     $39,777        $33,410
            Vendor non-trade receivables                                                 $33,180        $32,833
            Inventories                                                                   $5,718         $7,286
            Other current assets                                                         $14,585        $14,287
          Total current assets                                                          $147,957       $152,987
      Non-current assets:
            Marketable securities:                                                       $77,723        $91,479
            Property, plant and equipment, net                                           $49,834        $45,680
            Other non-current assets                                                     $83,727        $74,834
          Total non-current assets                                                      $211,284       $211,993
        Total assets                                                                    $359,241       $364,980
    LIABILITIES AND SHAREHOLDERS’ EQUITY:
      Current liabilities:
            Accounts payable                                                             $69,860        $68,960
            Other current liabilities                                                    $66,387        $78,304
            Deferred revenue                                                              $9,055         $8,249
            Commercial paper:                                                             $7,979         $9,967
            Commercial paper                                                              $8,000        $10,000
            Term debt                                                                    $12,350        $10,912
          Total current liabilities                                                     $165,631       $176,392
      Non-current liabilities:
            Term debt                                                                    $78,328        $85,750
            Other non-current liabilities                                                $41,549        $45,888
          Total non-current liabilities                                                 $119,877       $131,638
          Total liabilities                                                             $285,508       $308,030
          Commitments and contingencies
        Common stock, shares outstanding (in shares):                                 14,773,260     15,116,786
        Common stock, shares issued (in shares)                                       14,773,260     15,116,786
      Shareholders’ equity:
          Common stock and additional paid-in capital, $0.00001 par value:               $93,568        $83,276
    50,400,000 shares authorized; 14,773,260 and 15,116,786 shares issued and
    outstanding, respectively
          Accumulated deficit                                                          $(14,264)      $(19,154)
          Accumulated other comprehensive loss                                          $(5,571)       $(7,172)
          Total shareholders’ equity:                                                    $73,733        $56,950
        Total liabilities and shareholders’ equity                                      $359,241       $364,980

   Source: SEC XBRL  •  (In millions, except shares in thousands and per share data)

In [8]:
cashflow

                                       APPLE INC.   AAPL
                                       CONSOLIDATED STATEMENT OF CASH FLOWS
                                       Sep 30, 2023 to Sep 27, 2025

                                                                     Sep 27, 2025   Sep 28, 2024   Sep 30, 2023
   ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
      Cash, cash equivalents, and restricted cash and cash                $29,943        $30,737        $24,977
    equivalents, beginning balances
    Operating activities:
          Net income:                                                    $112,010        $93,736        $96,995
      Adjustments to reconcile net income to cash generated by
    operating activities:
          Depreciation and amortization                                   $11,698        $11,445        $11,519
          Share-based compensation expense                                $12,863        $11,688        $10,833
          Other                                                             $(89)       $(2,266)       $(2,227)
        Changes in operating assets and liabilities:
            Accounts receivable, net                                     $(6,682)       $(3,788)       $(1,688)
            Vendor non-trade receivables                                   $(347)       $(1,356)         $1,271
            Inventories                                                    $1,400       $(1,046)       $(1,618)
            Other current and non-current assets                         $(9,197)      $(11,731)       $(5,684)
            Accounts payable                                                 $902         $6,020       $(1,889)
            Other current and non-current liabilities                   $(11,076)        $15,552         $3,031
        Cash generated by operating activities                           $111,482       $118,254       $110,543
    Investing activities:
          Purchases of marketable securities                            $(24,407)      $(48,656)      $(29,513)
          Proceeds from maturities of marketable securities               $40,907        $51,211        $39,686
          Proceeds from sales of marketable securities                    $12,890        $11,135         $5,828
          Payments for acquisition of property, plant and               $(12,715)       $(9,447)      $(10,959)
    equipment
          Other                                                          $(1,480)       $(1,308)       $(1,337)
        Cash generated by investing activities                            $15,195         $2,935         $3,705
    Financing activities:
          Payments for taxes related to net share settlement of          $(5,960)       $(5,441)       $(5,431)
    equity awards:
          Restricted stock units                                         $(6,100)       $(5,600)       $(5,600)
          Payments for dividends and dividend equivalents               $(15,421)      $(15,234)      $(15,025)
          Repurchases of common stock                                   $(90,711)      $(94,949)      $(77,550)
          Proceeds from issuance of term debt, net                         $4,481                        $5,228
          Repayments of term debt                                       $(10,932)       $(9,958)      $(11,151)
          Proceeds from/(Repayments of) commercial paper, net            $(2,032)         $3,960       $(3,978)
          Other                                                            $(111)         $(361)         $(581)
        Cash used in financing activities                              $(120,686)     $(121,983)     $(108,488)
      Increase/(Decrease) in cash, cash equivalents, and                   $5,991         $(794)         $5,760
    restricted cash and cash equivalents
      Cash, cash equivalents, and restricted cash and cash                $35,934        $29,943        $30,737
    equivalents, ending balances
    Supplemental cash flow disclosure:
        Cash paid for income taxes, net                                   $43,369        $26,102        $18,679

   Source: SEC XBRL  •  (In millions, except shares and per share data)

In [9]:
financials

╭──────────────────────────────────── 10-K Apple Inc. (AAPL) • CIK 0000320193 ────────────────────────────────────╮
│   Fiscal Period       Fiscal Year 2025 (ended Sep 27, 2025)                                                     │
│   Data                1,131 facts • 182 contexts                                                                │
│                                                                                                                 │
│ Periods                                                                                                         │
│   Annual              FY 2025, FY 2024, FY 2023                                                                 │
│   (1 future period after 2025-09-27 excluded)                                                                   │
│                                                                                                                 │
│ Statements (72)                                                                                                 │
│   Statements        Income, Compr. Income, Balance Sheet, Equity, Cash Flow                                     │
│   Notes             Insider Trading Arrangements, Insider Trading Policies Proc, 9952165 - Disclosure - Debt, 9 │
│   Disclosures       Pvp Disclosure, Err Comp Disclosure, Award Timing Disclosure, 9955546 - Disclosure - Debt - │
│   Document          0000001 - Document - Cover Page, 0000002 - Document - Audit or Information                  │
╰───────────────────────────────────────────────────────────────────────── XBRL Data • xbrl.statements to browse ─╯

In [11]:
facts = apple.get_facts()
facts

╭───────────────────────────────────────── 📊 Apple Inc. Financial Facts ─────────────────────────────────────────╮
│                                                                                                                 │
│                                                                                                                 │
│ ╭─────────────────────────────────────────── 📈 Summary Statistics ───────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   CIK               320193                                                                                  │ │
│ │   Total Facts       25,135                                                                                  │ │
│ │   Unique Concepts   505                                                                                     │ │
│ │   Date Range        2009-07-22 to 2026-07-31                                                                │ │
│ │   Fiscal Years      2009 - 2026                                                                             │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────── 💰 Key Financial Metrics ────────────────────╮                                             │
│ │                                                                 │                                             │
│ │   Metric                            Value   Period    Quality   │                                             │
│ │  ─────────────────────────────────────────────────────────────  │                                             │
│ │   Total Assets           $383,266,000,000   Q3 2026   high      │                                             │
│ │   Total Liabilities      $275,746,000,000   Q3 2026   high      │                                             │
│ │   Public Float         $3,253,431,000,000   FY 2025   high      │                                             │
│ │   Shares Outstanding       14,594,180,000   Q3 2026   high      │                                             │
│ │                                                                 │                                             │
│ ╰─────────────────────────────────────────────────────────────────╯                                             │
│ ╭──────────────────── 📋 Available Statements ────────────────────╮                                             │
│ │                                                                 │                                             │
│ │   Statement Type        Fact Count                              │                                             │
│ │  ──────────────────────────────────                             │                                             │
│ │   BalanceSheet               3,359                              │                                             │
│ │   CashFlowStatement          3,964                              │                                             │
│ │   ComprehensiveIncome        1,298                              │                                             │
│ │   IncomeStatement            4,734                              │                                             │
│ │   StatementOfEquity            393                              │                                             │
│ │                                                                 │                                             │
│ ╰─────────────────────────────────────────────────────────────────╯                                             │
│ ╭───────── 📄 Recent Filings ─────────╮                  ╭────────── ✅ Data Quality ──────────╮                │
│ │                                     │                  │                                     │                │
│ │   Form     Latest Filing    Facts   │                  │   high Quality     24,566 (97.7%)   │                │
│ │  ─────────────────────────────────  │                  │   medium Quality   569 (2.3%)       │                │
│ │   10-Q     2026-07-31      15,304   │                  │   Audited Facts    9,262 (36.8%)    │                │
│ │   10-K     2025-10-31       8,503   │                  │                                     │                │
│ │   8-K      2015-01-28       1,118   │                  ╰─────────────────────────────────────╯                │
│ │   10-K/A   2010-01-25         210   │                                                                         │
│ │                                     │                                                                         │
│ ╰─────────────────────────────────────╯                                                                         │
╰────────────────────────────────────── SEC XBRL Facts • 25,135 total facts ──────────────────────────────────────╯

In [13]:
query = facts.query()
df = query.to_dataframe()

df.head()

,concept,label,value,numeric_value,unit,scale,period_start,period_end,period_type,fiscal_year,fiscal_period,filing_date,form_type,accession,data_quality,confidence_score,is_audited,is_estimated,statement_type
0,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",895816758.0,895816758.0,shares,None,None,2009-06-27,instant,2009,Q3,2009-07-22,10-Q,0001193125-09-153165,high,0.9,False,False,NaN
1,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",900678473.0,900678473.0,shares,None,None,2009-10-16,instant,2009,FY,2009-10-27,10-K,0001193125-09-214859,high,0.9,True,False,NaN
2,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",900678473.0,900678473.0,shares,None,None,2009-10-16,instant,2009,FY,2010-01-25,10-K/A,0001193125-10-012091,high,0.9,True,False,NaN
3,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",906794589.0,906794589.0,shares,None,None,2010-01-15,instant,2010,Q1,2010-01-25,10-Q,0001193125-10-012085,high,0.9,False,False,NaN
4,dei:EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",909938383.0,909938383.0,shares,None,None,2010-04-09,instant,2010,Q2,2010-04-21,10-Q,0001193125-10-088957,high,0.9,False,False,NaN

In [14]:
df.columns.tolist()

['concept',
 'label',
 'value',
 'numeric_value',
 'unit',
 'scale',
 'period_start',
 'period_end',
 'period_type',
 'fiscal_year',
 'fiscal_period',
 'filing_date',
 'form_type',
 'accession',
 'data_quality',
 'confidence_score',
 'is_audited',
 'is_estimated',
 'statement_type']

In [16]:
type(facts)

edgar.entity.entity_facts.EntityFacts

In [17]:
type(facts.query())

edgar.entity.query.FactQuery

In [26]:
df[
    df["concept"].str.contains(
        "LiabilitiesAndStockholdersEquity",
        case=False,
        na=False
    )
][
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "form_type"
    ]
].tail(20)

,concept,label,numeric_value,unit,period_end,fiscal_year,form_type
12100,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.525830e+11,USD,2023-09-30,2024,10-Q
12101,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.525830e+11,USD,2023-09-30,2024,10-K
12102,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.535140e+11,USD,2023-12-30,2024,10-Q
12103,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.374110e+11,USD,2024-03-30,2024,10-Q
12104,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.316120e+11,USD,2024-06-29,2024,10-Q
12105,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.649800e+11,USD,2024-09-28,2024,10-K
12106,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.649800e+11,USD,2024-09-28,2025,10-Q
12107,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.649800e+11,USD,2024-09-28,2025,10-Q
12108,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.649800e+11,USD,2024-09-28,2025,10-Q
12109,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.649800e+11,USD,2024-09-28,2025,10-K
12110,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.440850e+11,USD,2024-12-28,2025,10-Q
12111,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.312330e+11,USD,2025-03-29,2025,10-Q
12112,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.314950e+11,USD,2025-06-28,2025,10-Q
12113,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2025,10-K
12114,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,10-Q
12115,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,10-Q
12116,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,10-Q
12117,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.792970e+11,USD,2025-12-27,2026,10-Q
12118,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.710820e+11,USD,2026-03-28,2026,10-Q
12119,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.832660e+11,USD,2026-06-27,2026,10-Q

In [24]:
df[
    df["label"].str.contains("Liabil", case=False, na=False)
][["concept", "label"]].drop_duplicates()

,concept,label
433,us-gaap:AccruedLiabilities,Accrued Liabilities (Deprecated 2009-01-31)
435,us-gaap:AccruedLiabilitiesCurrent,"Accrued Liabilities, Current"
2255,us-gaap:BusinessAcquisitionPurchasePriceAlloca...,"Business Acquisition, Purchase Price Allocatio..."
2257,us-gaap:BusinessCombinationRecognizedIdentifia...,"Business Combination, Recognized Identifiable ..."
2261,us-gaap:BusinessCombinationRecognizedIdentifia...,"Business Combination, Recognized Identifiable ..."
4151,us-gaap:ContractWithCustomerLiability,"Contract with Customer, Liability"
4213,us-gaap:ContractWithCustomerLiabilityCurrent,"Contract with Customer, Liability, Current"
4275,us-gaap:ContractWithCustomerLiabilityRevenueRe...,"Contract with Customer, Liability, Revenue Rec..."
5253,us-gaap:DeferredIncomeTaxLiabilities,"Deferred Tax Liabilities, Gross"
5279,us-gaap:DeferredIncomeTaxLiabilitiesNet,"Deferred Income Tax Liabilities, Net"
5844,us-gaap:DeferredTaxLiabilities,"Deferred Tax Liabilities, Net"
5855,us-gaap:DeferredTaxLiabilitiesLeasingArrangements,"Deferred Tax Liabilities, Leasing Arrangements"
5867,us-gaap:DeferredTaxLiabilitiesNoncurrent,"Deferred Tax Liabilities, Net, Noncurrent"
5939,us-gaap:DeferredTaxLiabilitiesOther,"Deferred Tax Liabilities, Other"
5973,us-gaap:DeferredTaxLiabilitiesOtherComprehensi...,"Deferred Tax Liabilities, Other Comprehensive ..."
5983,us-gaap:DeferredTaxLiabilitiesUndistributedFor...,"Deferred Tax Liabilities, Undistributed Foreig..."
6010,us-gaap:DeferredTaxLiabilityNotRecognizedAmoun...,"Deferred Tax Liability Not Recognized, Amount ..."
7346,us-gaap:EmployeeRelatedLiabilitiesCurrent,"Employee-related Liabilities, Current"
7753,us-gaap:FairValueLiabilitiesMeasuredOnRecurrin...,"Fair Value, Liabilities Measured on Recurring ..."
7811,us-gaap:FinanceLeaseLiability,"Finance Lease, Liability"
7820,us-gaap:FinanceLeaseLiabilityCurrent,"Finance Lease, Liability, Current"
7831,us-gaap:FinanceLeaseLiabilityNoncurrent,"Finance Lease, Liability, Noncurrent"
7842,us-gaap:FinanceLeaseLiabilityPaymentsDue,"Finance Lease, Liability, Payment, Due"
7851,us-gaap:FinanceLeaseLiabilityPaymentsDueAfterY...,"Finance Lease, Liability, to be Paid, after Ye..."
7860,us-gaap:FinanceLeaseLiabilityPaymentsDueNextTw...,"Finance Lease, Liability, to be Paid, Year One"
7866,us-gaap:FinanceLeaseLiabilityPaymentsDueYearFive,"Finance Lease, Liability, to be Paid, Year Five"
7875,us-gaap:FinanceLeaseLiabilityPaymentsDueYearFour,"Finance Lease, Liability, to be Paid, Year Four"
7884,us-gaap:FinanceLeaseLiabilityPaymentsDueYearThree,"Finance Lease, Liability, to be Paid, Year Three"
7893,us-gaap:FinanceLeaseLiabilityPaymentsDueYearTwo,"Finance Lease, Liability, to be Paid, Year Two"
7902,us-gaap:FinanceLeaseLiabilityPaymentsRemainder...,"Finance Lease, Liability, to be Paid, Remainde..."
7905,us-gaap:FinanceLeaseLiabilityUndiscountedExces...,"Finance Lease, Liability, Undiscounted Excess ..."
8121,us-gaap:ForeignCurrencyDerivativeInstrumentsNo...,Foreign Currency Derivative Instruments Not De...
8127,us-gaap:ForeignCurrencyDerivativeLiabilitiesAt...,Foreign Currency Derivative Liabilities at Fai...
10150,us-gaap:IncreaseDecreaseInContractWithCustomer...,"Increase (Decrease) in Contract with Customer,..."
10611,us-gaap:IncreaseDecreaseInOtherOperatingLiabil...,Increase (Decrease) in Other Operating Liabili...
11760,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDue,"Lessee, Operating Lease, Liability, to be Paid"
11769,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11778,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11784,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11793,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11802,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11811,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,"Lessee, Operating Lease, Liability, to be Paid..."
11820,us-gaap:LesseeOperatingLeaseLiabilityPaymentsR...,"Lessee, Operating Lease, Liability, to be Paid..."
11823,us-gaap:LesseeOperatingLeaseLiabilityUndiscoun...,"Lessee, Operating Lease, Liability, Undiscount..."
11832,us-gaap:Liabilities,Liabilities
11976,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity
12120,us-gaap:LiabilitiesCurrent,"Liabilities, Current"
12264,us-gaap:LiabilitiesNoncurrent,"Liabilities, Noncurrent"
14575,us-gaap:OperatingLeaseLiability,"Operating Lease, Liability"
14584,us-gaap:OperatingLeaseLiabilityCurrent,"Operating Lease, Liability, Current"
14595,us-gaap:OperatingLeaseLiabilityNoncurrent,"Operating Lease, Liability, Noncurrent"
14782,us-gaap:OtherAccruedLiabilitiesCurrent,"Other Accrued Liabilities, Current"
14834,us-gaap:OtherAccruedLiabilitiesNoncurrent,"Other Accrued Liabilities, Noncurrent"
17080,us-gaap:OtherLiabilitiesCurrent,"Other Liabilities, Current"
17144,us-gaap:OtherLiabilitiesNoncurrent,"Other Liabilities, Noncurrent"
24991,us-gaap:HedgedLiabilityFairValueHedge,"Hedged Liability, Fair Value Hedge"
25023,us-gaap:DeferredTaxLiabilitiesPropertyPlantAnd...,"Deferred Tax Liabilities, Property, Plant and ..."

In [22]:
equity = df[
    df["label"].str.contains(
        "Stockholders.*Equity|Shareholders.*Equity",
        case=False,
        na=False,
        regex=True
    )
]

equity[
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "fiscal_period",
        "form_type",
        "filing_date"
    ]
].tail(20)

,concept,label,numeric_value,unit,period_end,fiscal_year,fiscal_period,form_type,filing_date
23336,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.679600e+10,USD,2025-03-29,2026,Q2,10-Q,2026-05-01
23337,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.679600e+10,USD,2025-03-29,2026,Q3,10-Q,2026-07-31
23338,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.583000e+10,USD,2025-06-28,2025,Q3,10-Q,2025-08-01
23339,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.583000e+10,USD,2025-06-28,2026,Q3,10-Q,2026-07-31
23340,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2025,FY,10-K,2025-10-31
23341,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q1,10-Q,2026-01-30
23342,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q2,10-Q,2026-05-01
23343,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q3,10-Q,2026-07-31
23344,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,8.819000e+10,USD,2025-12-27,2026,Q1,10-Q,2026-01-30
23345,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,8.819000e+10,USD,2025-12-27,2026,Q2,10-Q,2026-05-01
23346,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.064910e+11,USD,2026-03-28,2026,Q2,10-Q,2026-05-01
23347,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.064910e+11,USD,2026-03-28,2026,Q3,10-Q,2026-07-31
23348,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.075200e+11,USD,2026-06-27,2026,Q3,10-Q,2026-07-31
23349,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,2014,Q3,10-Q,2014-07-23
23350,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,2014,FY,10-K,2014-10-27
23351,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,0,,8-K,2015-01-28
23352,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2020,FY,10-K,2020-10-30
23353,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,Q1,10-Q,2021-01-28
23354,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,Q2,10-Q,2021-04-29
23355,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,Q3,10-Q,2021-07-28

In [27]:
df[
    df["concept"].str.contains(
        "StockholdersEquity",
        case=False,
        na=False
    )
][
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "form_type"
    ]
].tail(20)

,concept,label,numeric_value,unit,period_end,fiscal_year,form_type
23336,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.679600e+10,USD,2025-03-29,2026,10-Q
23337,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.679600e+10,USD,2025-03-29,2026,10-Q
23338,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.583000e+10,USD,2025-06-28,2025,10-Q
23339,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,6.583000e+10,USD,2025-06-28,2026,10-Q
23340,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2025,10-K
23341,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,10-Q
23342,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,10-Q
23343,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,10-Q
23344,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,8.819000e+10,USD,2025-12-27,2026,10-Q
23345,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,8.819000e+10,USD,2025-12-27,2026,10-Q
23346,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.064910e+11,USD,2026-03-28,2026,10-Q
23347,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.064910e+11,USD,2026-03-28,2026,10-Q
23348,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,1.075200e+11,USD,2026-06-27,2026,10-Q
23349,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,2014,10-Q
23350,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,2014,10-K
23351,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",7.000000e+00,number,2014-06-06,0,8-K
23352,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2020,10-K
23353,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,10-Q
23354,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,10-Q
23355,us-gaap:StockholdersEquityNoteStockSplitConver...,"Stockholders' Equity Note, Stock Split, Conver...",4.000000e+00,number,2020-08-28,2021,10-Q

In [28]:
equity_2025_09_27 = df[
    (df["concept"] == "us-gaap:StockholdersEquity") &
    (df["period_end"].astype(str) == "2025-09-27")
]

equity_2025_09_27[
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "fiscal_period",
        "form_type",
        "filing_date",
        "accession"
    ]
]

,concept,label,numeric_value,unit,period_end,fiscal_year,fiscal_period,form_type,filing_date,accession
23340,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2025,FY,10-K,2025-10-31,0000320193-25-000079
23341,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q1,10-Q,2026-01-30,0000320193-26-000006
23342,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q2,10-Q,2026-05-01,0000320193-26-000013
23343,us-gaap:StockholdersEquity,Stockholders' Equity Attributable to Parent,7.373300e+10,USD,2025-09-27,2026,Q3,10-Q,2026-07-31,0000320193-26-000020

In [29]:
assets_2025_09_27 = df[
    (df["concept"] == "us-gaap:Assets") &
    (df["period_end"].astype(str) == "2025-09-27")
]

assets_2025_09_27[
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "fiscal_period",
        "form_type",
        "filing_date",
        "accession"
    ]
]

,concept,label,numeric_value,unit,period_end,fiscal_year,fiscal_period,form_type,filing_date,accession
1433,us-gaap:Assets,Assets,3.592410e+11,USD,2025-09-27,2025,FY,10-K,2025-10-31,0000320193-25-000079
1434,us-gaap:Assets,Assets,3.592410e+11,USD,2025-09-27,2026,Q1,10-Q,2026-01-30,0000320193-26-000006
1435,us-gaap:Assets,Assets,3.592410e+11,USD,2025-09-27,2026,Q2,10-Q,2026-05-01,0000320193-26-000013
1436,us-gaap:Assets,Assets,3.592410e+11,USD,2025-09-27,2026,Q3,10-Q,2026-07-31,0000320193-26-000020

In [30]:
total_2025_09_27 = df[
    (df["concept"] == "us-gaap:LiabilitiesAndStockholdersEquity") &
    (df["period_end"].astype(str) == "2025-09-27")
]

total_2025_09_27[
    [
        "concept",
        "label",
        "numeric_value",
        "unit",
        "period_end",
        "fiscal_year",
        "fiscal_period",
        "form_type",
        "filing_date",
        "accession"
    ]
]

,concept,label,numeric_value,unit,period_end,fiscal_year,fiscal_period,form_type,filing_date,accession
12113,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2025,FY,10-K,2025-10-31,0000320193-25-000079
12114,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,Q1,10-Q,2026-01-30,0000320193-26-000006
12115,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,Q2,10-Q,2026-05-01,0000320193-26-000013
12116,us-gaap:LiabilitiesAndStockholdersEquity,Liabilities and Equity,3.592410e+11,USD,2025-09-27,2026,Q3,10-Q,2026-07-31,0000320193-26-000020

In [31]:
tenk = apple.get_filings(form="10-K").latest()
xbrl = tenk.xbrl()
bs = xbrl.statements.balance_sheet()
bs_df = bs.to_dataframe()

In [32]:
bs_df.columns.tolist()

['concept',
 'label',
 'standard_concept',
 '2025-09-27',
 '2024-09-28',
 'level',
 'abstract',
 'dimension',
 'is_breakdown',
 'dimension_axis',
 'dimension_member',
 'dimension_member_label',
 'dimension_label',
 'balance',
 'weight',
 'preferred_sign',
 'parent_concept',
 'parent_abstract_concept']

In [33]:
bs_df[
    bs_df["standard_concept"].isin([
        "Assets",
        "LiabilitiesAndStockholdersEquity",
        "StockholdersEquity"
    ])
][[
    "concept",
    "label",
    "standard_concept",
    "2025-09-27",
    "2024-09-28"
]]

           concept         label standard_concept    2025-09-27    2024-09-28
51  us-gaap_Assets  Total assets           Assets  3.592410e+11  3.649800e+11

In [34]:
bs_df[
    bs_df["label"].str.contains(
        "Liabil|Equity",
        case=False,
        na=False
    )
][[
    "concept",
    "label",
    "standard_concept",
    "2025-09-27",
    "2024-09-28"
]].head(50)

,concept,label,standard_concept,2025-09-27,2024-09-28
52,us-gaap_LiabilitiesAndStockholdersEquityAbstract,LIABILITIES AND SHAREHOLDERS’ EQUITY:,NaN,NaN,NaN
53,us-gaap_LiabilitiesCurrentAbstract,Current liabilities:,NaN,NaN,NaN
55,us-gaap_OtherLiabilitiesCurrent,Other current liabilities,OtherNonOperatingCurrentLiabilities,6.638700e+10,7.830400e+10
60,us-gaap_LiabilitiesCurrent,Total current liabilities,CurrentLiabilitiesTotal,1.656310e+11,1.763920e+11
61,us-gaap_LiabilitiesNoncurrentAbstract,Non-current liabilities:,NaN,NaN,NaN
63,us-gaap_OtherLiabilitiesNoncurrent,Other non-current liabilities,OtherNonOperatingNonCurrentLiabilities,4.154900e+10,4.588800e+10
64,us-gaap_LiabilitiesNoncurrent,Total non-current liabilities,NonCurrentLiabilitiesTotal,1.198770e+11,1.316380e+11
65,us-gaap_Liabilities,Total liabilities,Liabilities,2.855080e+11,3.080300e+11
70,us-gaap_StockholdersEquityAbstract,Shareholders’ equity:,NaN,NaN,NaN
74,us-gaap_StockholdersEquity,Total shareholders’ equity,AllEquityBalance,7.373300e+10,5.695000e+10
78,us-gaap_LiabilitiesAndStockholdersEquity,Total liabilities and shareholders’ equity,LiabilitiesAndEquity,3.592410e+11,3.649800e+11

In [35]:
bs_df[
    bs_df["standard_concept"].astype(str).str.contains(
        "Liabil|Equity",
        case=False,
        na=False
    )
][[
    "concept",
    "label",
    "standard_concept",
    "2025-09-27",
    "2024-09-28"
]].head(50)

,concept,label,standard_concept,2025-09-27,2024-09-28
55,us-gaap_OtherLiabilitiesCurrent,Other current liabilities,OtherNonOperatingCurrentLiabilities,6.638700e+10,7.830400e+10
56,us-gaap_ContractWithCustomerLiabilityCurrent,Deferred revenue,OtherOperatingCurrentLiabilities,9.055000e+09,8.249000e+09
60,us-gaap_LiabilitiesCurrent,Total current liabilities,CurrentLiabilitiesTotal,1.656310e+11,1.763920e+11
63,us-gaap_OtherLiabilitiesNoncurrent,Other non-current liabilities,OtherNonOperatingNonCurrentLiabilities,4.154900e+10,4.588800e+10
64,us-gaap_LiabilitiesNoncurrent,Total non-current liabilities,NonCurrentLiabilitiesTotal,1.198770e+11,1.316380e+11
65,us-gaap_Liabilities,Total liabilities,Liabilities,2.855080e+11,3.080300e+11
71,us-gaap_CommonStocksIncludingAdditionalPaidInC...,"Common stock and additional paid-in capital, $...",CommonEquity,9.356800e+10,8.327600e+10
74,us-gaap_StockholdersEquity,Total shareholders’ equity,AllEquityBalance,7.373300e+10,5.695000e+10
78,us-gaap_LiabilitiesAndStockholdersEquity,Total liabilities and shareholders’ equity,LiabilitiesAndEquity,3.592410e+11,3.649800e+11

In [36]:
assets = bs_df.loc[
    bs_df["standard_concept"] == "Assets",
    "2025-09-27"
].iloc[0]

liabilities = bs_df.loc[
    bs_df["standard_concept"] == "Liabilities",
    "2025-09-27"
].iloc[0]

equity = bs_df.loc[
    bs_df["standard_concept"] == "AllEquityBalance",
    "2025-09-27"
].iloc[0]

liab_equity = bs_df.loc[
    bs_df["standard_concept"] == "LiabilitiesAndEquity",
    "2025-09-27"
].iloc[0]

print("Assets:", assets)
print("Liabilities:", liabilities)
print("Equity:", equity)
print("Liabilities + Equity:", liab_equity)

Assets: 359241000000.0
Liabilities: 285508000000.0
Equity: 73733000000.0
Liabilities + Equity: 359241000000.0

In [37]:
residual_1 = assets - (liabilities + equity)
residual_2 = assets - liab_equity

print("Assets - (Liabilities + Equity):", residual_1)
print("Assets - reported LiabilitiesAndEquity:", residual_2)

Assets - (Liabilities + Equity): 0.0
Assets - reported LiabilitiesAndEquity: 0.0