In [17]:
from edgar import Company, set_identity

set_identity("Kedar Haldar kedar.haldar11@gmail.com")

In [18]:
from pathlib import Path
import pandas as pd
import pyarrow.dataset as ds
import pyarrow.parquet as pq

root = Path(
    r"C:\Users\kedar\OneDrive\Documents\GitHub\Finance-GraphRag"
)
folder = root / "data" / "finreflectkg" / "data"

files = sorted(folder.glob("*.parquet"))

print(len(files))       # Number of files
print(files[0].name)    # First filename
print(folder.exists()) # Does the folder exist?

103
train-00000-of-00103.parquet
True

In [19]:
df = pd.read_parquet(files[0])
print("File:", files[0].name)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head(3))

File: train-00000-of-00103.parquet
Shape: (170033, 18)
Columns: ['triplet_id', 'entity', 'entity_type', 'relationship', 'target', 'target_type', 'start_date', 'end_date', 'extraction_type', 'ticker', 'year', 'source_file', 'page_id', 'chunk_id', 'chunk_text', 'triplet_length', 'chunk_text_length', 'has_context']

,triplet_id,entity,entity_type,relationship,target,target_type,start_date,end_date,extraction_type,ticker,year,source_file,page_id,chunk_id,chunk_text,triplet_length,chunk_text_length,has_context
0,ctas_2014_page_1_chunk_1_triplet_1,ctas,ORG,subject_to,sec regulation,REGULATORY_REQUIREMENT,January 2014,default_end_timestamp,default,CTAS,2014,CTAS_10k_2014.pdf,page_1,chunk_1,## UNITED STATES SECURITIES AND EXCHANGE COMMI...,30,3578,True
1,ctas_2014_page_1_chunk_1_triplet_2,ctas,ORG,operates_in,united state,GPE,January 2014,default_end_timestamp,default,CTAS,2014,CTAS_10k_2014.pdf,page_1,chunk_1,## UNITED STATES SECURITIES AND EXCHANGE COMMI...,29,3578,True
2,ctas_2014_page_1_chunk_1_triplet_3,ctas,ORG,discloses,common stock,FIN_INST,November 2013,default_end_timestamp,default,CTAS,2014,CTAS_10k_2014.pdf,page_1,chunk_1,## UNITED STATES SECURITIES AND EXCHANGE COMMI...,27,3578,True

In [20]:
display(df["relationship"].value_counts().head(30))

relationship
discloses             73824
depends_on             9492
subject_to             9206
operates_in            9033
negatively_impacts     7451
impacted_by            5940
has_stake_in           4985
increase               4180
introduces             3928
face                   3373
decrease               2669
invests_in             2136
announces              2086
produce                1754
complies_with          1740
guides_on              1540
partners_with          1521
positively_impacts     1345
impact                  998
regulates               801
offer                   787
supply                  757
include                 719
involved_in             690
us                      682
issue                   640
competes_with           613
serves_as               504
recognizes              479
provide                 476
Name: count, dtype: int64

In [21]:
sample = df[df["relationship"] == "discloses"].sample(
    n=5, random_state=42
)

for _, row in sample.iterrows():
    print("ID:", row["triplet_id"])
    print("Claim:", row["entity"], "→", row["relationship"], "→", row["target"])
    print("Source:", row["source_file"])
    print("Text:", row["chunk_text"])
    print("-" * 80)

ID: well_2024_page_77_chunk_1_triplet_74
Claim: well → discloses → total current liability
Source: WELL_10k_2024.pdf
Text: Item 7. Management's Discussion and Analysis of Financial Condition and Results of Operations
--------------------------------------------------------------------------------
ID: cnp_2020_page_3_chunk_2_triplet_6
Claim: cnp → discloses → financial statement and supplementary data
Source: CNP_10k_2020.pdf
Text: | | | Page | |----------|--------------------------------------------------------------------------------------------------------------|----------| | Item 1. | Business | 1 | | Item 1A. | Risk Factors | 20 | | Item 1B. | Unresolved Staff Comments | 40 | | Item 2. | Properties | 41 | | Item 3. | Legal Proceedings | 43 | | Item 4. | Mine Safety Disclosures | 43 | | PART II | PART II | PART II | | Item 5. | Market for Registrants' Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities | 43 | | Item 6. | Selected Financial Data | 43 | | Item 7. | Management's Discussion and Analysis of Financial Condition and Results of Operations | 44 | | Item 7A. | Quantitative and Qualitative Disclosures About Market Risk | 86 | | Item 8. | Financial Statements and Supplementary Data | 88 | | Item 9. | Changes in and Disagreements with Accountants on Accounting and Financial Disclosure | 189 | | Item 9A. | Controls and Procedures | 190 | | Item 9B. | Other Information | 192 | | PART III | PART III | PART III | | Item 10. | Directors, Executive Officers and Corporate Governance | 192 | | Item 11. | Executive Compensation | 193 | | Item 12. | Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters | 193 | | Item 13. | Certain Relationships and Related Transactions, and Director Independence | 193 | | Item 14. | Principal Accounting Fees and Services | 193 | | PART IV | PART IV | PART IV | | Item 15. | Exhibits and Financial Statement Schedules | 194 | | Item 16. | Form 10-K Summary | 194 |
--------------------------------------------------------------------------------
ID: ctas_2024_page_27_chunk_2_triplet_3
Claim: ctas → discloses → interest payment due one year or less
Source: CTAS_10k_2024.pdf
Text: | | Payments Due byPeriod | Payments Due byPeriod | Payments Due byPeriod | Payments Due byPeriod | Payments Due byPeriod | |-------------------------------------------------------|-------------------------|-------------------------|-------------------------|-------------------------|-------------------------| | (Inthousands) | Total | One year or less | Two to three years | Four to five years | After five years | | Debt (1) | $ 2,486,550 | $ 450,000 | $ 1,000,000 | $ - | $ 1,036,550 | | Operating leases (2) | 211,469 | 51,323 | 79,583 | 50,352 | 30,211 | | Interest payments | 563,114 | 97,814 | 167,096 | 93,096 | 205,108 | | Total contractual and other material cash obligations | $ 3,261,133 | $ 599,137 | $ 1,246,679 | $ 143,448 | $ 1,271,869 |
--------------------------------------------------------------------------------
ID: amzn_2017_page_56_chunk_5_triplet_9
Claim: amzn → discloses → no borrowing outstanding
Source: AMZN_10k_2017.pdf
Text: On September 5, 2014, we entered into an unsecured revolving credit facility (the 'Credit Agreement') with a syndicate of lenders that provides us with a borrowing capacity of up to $2.0 billion. The Credit Agreement has a term of two years, but it may be extended for up to three additional one-year terms if approved by the lenders. The initial interest rate applicable to outstanding balances under the Credit Agreement is the London interbank offered rate ('LIBOR') plus 0.625%, under our current credit ratings. If our credit ratings are downgraded this rate could increase to as much as LIBOR plus 1.00%. There were no borrowings outstanding under the Credit Agreement as of December 31, 2015 and 2014.
--------------------------------------------------------------------------------
ID: well_2021_page_58_chunk_1_triplet_49
Claim: well → discloses → price to book ratio
Source: WELL_10k_2021.pdf
Text: ## Item 7. Management's Discussion and Analysis of Financial Condition and Results of Operations
--------------------------------------------------------------------------------

In [22]:
amazon = sample[
    sample["triplet_id"] == "amzn_2017_page_56_chunk_5_triplet_9"
]

print(amazon[[
    "entity", "relationship", "target",
    "start_date", "end_date", "year", "source_file"
]].to_string(index=False))

entity relationship                   target    start_date      end_date  year       source_file
  amzn    discloses no borrowing outstanding December 2015 December 2015  2017 AMZN_10k_2017.pdf

### Example: Amazon borrowing claim

Triple ID: amzn_2017_page_56_chunk_5_triplet_9

- Graph claim: Amazon discloses no borrowing outstanding.
- Stored dates: December 2015 to December 2015.
- Source text: No borrowings under a specific credit agreement
  as of December 31, 2015 and 2014.
- Issue: The triple omits the credit-agreement scope and the
  additional 2014 date.
- XBRL verification: Not yet attempted. Requires a fact for
  that facility and date; total company debt is not equivalent.

In [23]:
changes = df[
    df["relationship"].isin(["increase", "decrease"])
].sample(n=5, random_state=42)

for _, row in changes.iterrows():
    print("ID:", row["triplet_id"])
    print("Claim:", row["entity"], "→", row["relationship"], "→", row["target"])
    print("Dates:", row["start_date"], "→", row["end_date"])
    print("Source:", row["source_file"])
    print("Text:", row["chunk_text"])
    print("-" * 80)

ID: cnp_2017_page_48_chunk_1_triplet_20
Claim: cnp → increase → compliance expense
Dates: January 2017 → December 2017
Source: CNP_10k_2017.pdf
Text: temperatures for the rest of the year, including the summer months, in the Houston area. In 2013, we experienced a colder than normal spring and very cold weather in November and December in Houston and all of the states in which we have gas customers. Our long-term national trends indicate customers have reduced their energy consumption, and reduced consumption can adversely affect our results. However, due to more affordable energy prices and continued economic improvement in the areas we serve, the trend toward lower usage has slowed in some of the areas we serve. In addition, in many of our service areas, particularly in the Houston area and in Minnesota, we have benefited from a growth in the number of customers that also tends to mitigate the effects of reduced consumption. We anticipate that this trend will continue as the regions' economies continue to grow. The profitability of our businesses is influenced significantly by the regulatory treatment we receive from the various state and local regulators who set our electric and gas distribution rates. Our Energy Services business segment contracts with customers for transportation, storage and sales of natural gas on an unregulated basis. Its operations serve customers in the central United States. The segment benefits from favorable price differentials, either on a geographic basis or on a seasonal basis. While this business utilizes financial derivatives to hedge its ex posure to price movements, it does not engage in speculative or proprietary trading and maintains a low value at risk level, or V aR, to avoid significant financial ex posures. In 2015 and 2014, Energy Services exhibited strong commercial and industrial customer results while capitalizing on asset optimization opportunities created by basis volatility. Extreme cold weather in 2014 also increased throughput and margin from our weather sensitive customers. The nature of our businesses requires significant amounts of capital investment, and we rely on internally generated cash, borrowings under our credit facilities, proceeds from commercial paper and issuances of debt and equity in the capital markets to satisfy these capital needs. We strive to maintain investment grade ratings for our securities in order to access the capital markets on terms we consider reasonable. A reduction in our ratings generally would increase our borrowing costs for new issuances of debt, as well as borrowing costs under our existing revolving credit facilities, and may prevent us from accessing the commercial paper markets. Disruptions in the financial markets can also affect the availability of new capital on terms we consider attractive. In those circumstances, companies like us may not be able to obtain certain types of external financing or may be required to accept terms less favorable than they would otherwise accept. For that reason, we seek to maintain adequate liquidity for our businesses through existing credit facilities and prudent refinancing of ex isting debt. The regulation of natural gas pipelines and related facilities by federal and state regulatory agencies affects our business. In accordance with natural gas pipeline safety and integrity regulations, we are making, and will continue to make, significant capital investments in our service territories, which are necessary to help operate and maintain a safe, reliable and growing natural gas system. Our compliance expenses may also increase as a result of preventative measures required under these regulations. Consequently, new rates in the areas we serve are necessary to recover these increasing costs. We expect to make contributions to our pension plans aggregating approximately $8 million in 2016 but may need to make larger contributions in subsequent years. Consistent with the regulatory treatment of such costs, we can defer the amount of pension expense that differs from the level of pension expense included in our base rates for our Electric Transmission &amp; Distribution business segment and Natural Gas Distribution business segment in Texas. ## Factors Influencing Our Midstream Investments Segment The results of our Midstream Investments segment are primarily dependent upon the results of Enable, which are driven primarily by the volume of natural gas, NGLs and crude oil that Enable gathers, processes and transports across its systems, which depends significantly on the level of production from natural gas wells connected to its systems across a number of U.S. mid-continent markets. Aggregate production volumes are affected by the overall amount of oil and gas drilling and completion activities, as production must be maintained or increased by new drilling or other activity, because the production rate of oil and gas wells declines over time. Oil and gas producers' willingness to engage in new drilling is determined by a number of factors, the most important of which are the prevailing and projected prices of natural gas, NGLs and crude oil, the cost to drill and operate a well, the availability and cost of capital and environmental and government regulations. Commodity price changes impact the commodity-based portion of Enable's gross margin, its producer customers' decisions to drill and complete wells and its transportation and storage customers decisions to contract capacity on Enable's system. Prices of natural gas, crude oil, and NGLs have historically experienced periods of significant volatility. Enable's results are also impacted by the price differentials between receipt and delivery points on its systems. Enable has attempted to mitigate the impact of commodity prices on its business by entering into hedges, focusing on contracting fee-based business, and converting existing commoditybased contracts to fee-based contracts. The prices of crude oil, NGLs and natural gas have continued to decline significantly. Over the course of 2015 and continuing into 2016, natural gas and crude oil prices have dropped to their lowest levels in over 10 years from a high of $13.31 per MMBtu in July 2008 to $1.63 per MMBtu at December 23, 2015 and $145.31 per barrel in July 2008 to $26.19 per barrel at February 11, 2016, respectively.
--------------------------------------------------------------------------------
ID: vz_2015_page_28_chunk_2_triplet_4
Claim: vz → increase → allowance for uncollectible account receivable
Dates: January 2014 → December 2014
Source: VZ_10k_2015.pdf
Text: | | | | | | (dollars in millions) | |--------------------------------------------------|--------------------------------|--------------------|--------------------------------------|------------------------|-------------------------| | | | Additions | Additions | | | | Description | Balance at Beginning of Period | Chargedto Expenses | Chargedto Other Accounts Note (a)(b) | Deductions Note (c)(d) | Balance at Endof Period | | Allowance for Uncollectible Accounts Receivable: | | | | | | | Year 2015 (e) | $ 739 | $ 1,610 | $ 200 | $ 1,512 | $ 1,037 | | Year 2014 | 645 | 1,095 | 141 | 1,142 | 739 | | Year 2013 | 641 | 993 | 162 | 1,151 | 645 | | Valuation Allowance for Deferred TaxAssets: | | | | | | | Year 2015 | $ 1,841 | $ 237 | $ 1,701 | $ 365 | $ 3,414 | | Year 2014 | 1,685 | 505 | 5 | 354 | 1,841 | | Year 2013 | 2,096 | 235 | 64 | 710 | 1,685 |
--------------------------------------------------------------------------------
ID: vz_2021_page_35_chunk_1_triplet_29
Claim: vz → increase → dividend payout
Dates: January 2021 → December 2021
Source: VZ_10k_2021.pdf
Text: ## Table of Contents and secondary lines and switched to alternative technologies such as wireless, Voice over Internet Protocol, and cable for voice and data services. In our Business segment, we offer wireless products and services to business and government customers across the U.S. We continue to grow our retail connections while operating in a competitive environment. We expect that this connection growth, combined with our industry-leading network assets, will provide additional opportunities to sell solutions, such as those around security, advanced communications and professional services. We also expect to expand our existing services offered to business customers through our Intelligent Edge Network, our multi-use platform. In addition, in both our Consumer and our Business segments, we expect to support connection growth in part by adding capacity and density to our 4G LTE network, and by leading the build-out of our 5G network. We also anticipate the continued migration of 3G connections onto 4G and 5G technologies with the expected cessation of 3G services. ## 2022 Operating Revenue Trends In our Consumer segment, we expect to see a continuation of service revenue growth in 2022 as customers shift to higher access plans with additional services and increase the number of devices they connect with our networks and services. We expect continued growth in wireless service revenue, driven by Tracfone contributions, migrations to higher priced plans and increases in fixed wireless access connections. We expect Fios revenue to benefit in 2022 as growth in our broadband customer base and increases in demand for higher speed internet connections offsets the impact of the shift from the triple-play bundle to standalone service. In our Business segment, we expect wireless revenue to expand, driven by growth from increases in wireless volumes and fixed wireless access contributions. We expect that Fios, through increased penetration, will also contribute to revenue growth. Legacy traditional wireline services will continue to face secular pressures. On September 1, 2021, we completed the sale of Verizon Media. We expect to see a decrease in operating revenues as a result of this divestiture. ## 2022 Operating Expense and Cash Flow from Operations Trends We expect our consolidated operating income margin and adjusted consolidated EBITDA margin to remain strong as we continue to drive revenue growth and undertake initiatives to reduce our overall cost structure by improving productivity and gaining efficiencies in our operations throughout the business in 2022 and beyond. Business Excellence initiatives include zero-based budgeting methodology, driving capital efficiencies from the architecture of the networks and evolving our Information Technology strategy. We believe our additional investments in our Business segment in both product simplification and continued focus on process improvements and new work tools will drive cost savings and create incremental growth opportunities in areas such as 5G and One Fiber. We create value for our shareholders by investing the cash flows generated by our business in opportunities and transactions that support continued profitable growth, thereby increasing customer satisfaction and usage of our products and services. In addition, we have used our cash flows to maintain and grow our dividend payout to shareholders. Verizon's Board of Directors increased the Company's quarterly dividend by 2.0% during 2021, making this the fifteenth consecutive year in which we have raised our dividend. Our goal is to use our cash to create long-term value for our shareholders. We will continue to look for investment opportunities that will help us to grow the business, strengthen our balance sheet, acquire spectrum licenses (see "Cash Flows from Investing Activities"), pay dividends to our shareholders and, when appropriate, buy back shares of our outstanding common stock (see "Cash Flows from Financing Activities"). ## Liquidity and Capital Resources We use the net cash generated from our operations to fund expansion and modernization of our networks, service and repay external financing, pay dividends, invest in new businesses and spectrum and, when appropriate, buy back shares of our outstanding common stock. Our sources of funds, primarily from operations and, to the extent necessary, from external financing arrangements, are sufficient to meet ongoing operating and investing requirements over the next 12 months and beyond. Our cash and cash equivalents balance is $2.9 billion as of December 31, 2021, consistent with historical pre-pandemic levels. Our cash and cash equivalents are held both domestically and internationally, and are invested to maintain principal and provide liquidity. See "Market Risk" for additional information regarding our foreign currency risk management strategies. We expect that our capital spending requirements will continue to be financed primarily through internally generated funds. Debt or equity financing may be needed to fund additional investments or development activities, such as the completion of business acquisitions, the acquisition of additional wireless spectrum, or to maintain an appropriate capital structure to ensure our financial flexibility. Our available external financing arrangements include an active commercial paper program, credit available under credit facilities and other bank lines of credit, vendor financing arrangements, issuances of registered debt or equity securities, U.S. retail medium-term notes and other capital market securities that are privately-placed or offered overseas. In addition, we monetize our device payment plan agreement receivables through asset-backed debt transactions.
--------------------------------------------------------------------------------
ID: pom_2015_page_91_chunk_2_triplet_4
Claim: pom → increase → common stock issue
Dates: January 2015 → December 2015
Source: POM_10k_2015.pdf
Text: | | Cash (Use) Source | Cash (Use) Source | Cash (Use) Source | |-------------------------------------------------------------------------------------------------------------------------------|-----------------------|-----------------------|-----------------------| | | 2015 | 2014 | 2013 | | | (millions of dollars) | (millions of dollars) | (millions of dollars) | | Dividends paid on common stock | $(275) | $(272) | $(270) | | Common stock issued for the Direct Stock Purchase and Dividend Reinvestment Plan (DRP) and employee- related compensation (a) | 18 | 34 | 50 | | Issuances of common stock | - | - | 324 | | Issuance of Series A preferred stock | 54 | 126 | - | | Issuances of long-termdebt | 558 | 766 | 800 | | Reacquisitions of long-termdebt | (420) | (334) | (558) | | Issuances (repayments) of short-termdebt, net | 34 | 164 | (200) | | Borrowings under termloans | 300 | - | 250 | | Repayments of termloans | - | (100) | (450) | | Cost of issuances | (7) | (10) | (23) | | Net other financing activities | (29) | (11) | (11) | | Net cash from(used by) financing activities | $ 233 | $ 363 | $ (88) |
--------------------------------------------------------------------------------
ID: pom_2015_page_76_chunk_3_triplet_9
Claim: pom → increase → transmission revenue
Dates: June 2013 → December 2015
Source: POM_10k_2015.pdf
Text: Regulated T&amp;D Electric Revenue increased by $131 million primarily due to: - An increase of $81 million due to electric distribution base rate increases (Pepco in the District of Columbia effective April 2014, and in Maryland effective July 2013 and July 2014; DPL in Maryland effective September 2013, and in Delaware effective October 2013; ACE effective July 2013 and September 2014). - An increase of $20 million in transmission revenue resulting from higher rates effective June 2014 and June 2013 related to increases in transmission plant investment and operating expenses, partially offset by the establishment of a reserve related to the FERC ROE challenges. - An increase of $19 million due to an EmPower Maryland rate increase effective February 2014 (which is substantially offset by a corresponding increase in Depreciation and Amortization).
--------------------------------------------------------------------------------

In [24]:
candidate = df.loc[
    df["triplet_id"] == "vz_2015_page_28_chunk_2_triplet_4"
].iloc[0]

print(candidate["triplet_id"])
print(candidate["chunk_text"])

vz_2015_page_28_chunk_2_triplet_4
| | | | | | (dollars in millions) | |--------------------------------------------------|--------------------------------|--------------------|--------------------------------------|------------------------|-------------------------| | | | Additions | Additions | | | | Description | Balance at Beginning of Period | Chargedto Expenses | Chargedto Other Accounts Note (a)(b) | Deductions Note (c)(d) | Balance at Endof Period | | Allowance for Uncollectible Accounts Receivable: | | | | | | | Year 2015 (e) | $ 739 | $ 1,610 | $ 200 | $ 1,512 | $ 1,037 | | Year 2014 | 645 | 1,095 | 141 | 1,142 | 739 | | Year 2013 | 641 | 993 | 162 | 1,151 | 645 | | Valuation Allowance for Deferred TaxAssets: | | | | | | | Year 2015 | $ 1,841 | $ 237 | $ 1,701 | $ 365 | $ 3,414 | | Year 2014 | 1,685 | 505 | 5 | 354 | 1,841 | | Year 2013 | 2,096 | 235 | 64 | 710 | 1,685 |

In [25]:
verizon = Company("VZ")
vz_facts = verizon.get_facts()
vz_df = vz_facts.query().to_dataframe()

allowance_concepts = vz_df[
    vz_df["concept"].str.contains(
        "Allowance|Uncollectible|Doubtful",
        case=False,
        na=False
    )
][["concept", "label"]].drop_duplicates()

display(allowance_concepts)
print(allowance_concepts.to_string(index=False))

,concept,label
1122,us-gaap:AllowanceForDoubtfulAccountsPremiumsAn...,"Allowance for Doubtful Accounts, Premiums and ..."
1130,us-gaap:AllowanceForDoubtfulAccountsReceivable...,"Accounts Receivable, Allowance for Credit Loss..."
6807,us-gaap:DeferredTaxAssetsTaxDeferredExpenseRes...,"Deferred Tax Assets, Tax Deferred Expense, Res..."
6815,us-gaap:DeferredTaxAssetsValuationAllowance,"Deferred Tax Assets, Valuation Allowance"
10018,us-gaap:FinancingReceivableAllowanceForCreditL...,"Financing Receivable, Allowance for Credit Loss"
10139,us-gaap:FinancingReceivableAllowanceForCreditL...,"Financing Receivable, Allowance for Credit Los..."
24123,us-gaap:ProvisionForDoubtfulAccounts,"Accounts Receivable, Credit Loss Expense (Reve..."
27530,us-gaap:ValuationAllowancesAndReservesPeriodIn...,"SEC Schedule, 12-09, Valuation Allowances and ..."
28785,us-gaap:EffectiveIncomeTaxRateReconciliationCh...,"Effective Income Tax Rate Reconciliation, Chan..."
28827,us-gaap:IncomeTaxReconciliationChangeInDeferre...,"Effective Income Tax Rate Reconciliation, Chan..."
28881,us-gaap:ValuationAllowanceDeferredTaxAssetChan...,"Valuation Allowance, Deferred Tax Asset, Incre..."

                                                                                   concept                                                                                                label
                           us-gaap:AllowanceForDoubtfulAccountsPremiumsAndOtherReceivables                                      Allowance for Doubtful Accounts, Premiums and Other Receivables
                                     us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent                                              Accounts Receivable, Allowance for Credit Loss, Current
us-gaap:DeferredTaxAssetsTaxDeferredExpenseReservesAndAccrualsAllowanceForDoubtfulAccounts    Deferred Tax Assets, Tax Deferred Expense, Reserves and Accruals, Allowance for Doubtful Accounts
                                               us-gaap:DeferredTaxAssetsValuationAllowance                                                             Deferred Tax Assets, Valuation Allowance
                                       us-gaap:FinancingReceivableAllowanceForCreditLosses                                                      Financing Receivable, Allowance for Credit Loss
                              us-gaap:FinancingReceivableAllowanceForCreditLossesWriteOffs                                            Financing Receivable, Allowance for Credit Loss, Writeoff
                                                      us-gaap:ProvisionForDoubtfulAccounts                                                  Accounts Receivable, Credit Loss Expense (Reversal)
                              us-gaap:ValuationAllowancesAndReservesPeriodIncreaseDecrease                   SEC Schedule, 12-09, Valuation Allowances and Reserves, Period Increase (Decrease)
   us-gaap:EffectiveIncomeTaxRateReconciliationChangeInDeferredTaxAssetsValuationAllowance Effective Income Tax Rate Reconciliation, Change in Deferred Tax Assets Valuation Allowance, Percent
                us-gaap:IncomeTaxReconciliationChangeInDeferredTaxAssetsValuationAllowance  Effective Income Tax Rate Reconciliation, Change in Deferred Tax Assets Valuation Allowance, Amount
                                  us-gaap:ValuationAllowanceDeferredTaxAssetChangeInAmount                                 Valuation Allowance, Deferred Tax Asset, Increase (Decrease), Amount

In [26]:
concept = "us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent"

matches = vz_df[
    (vz_df["concept"] == concept)
    & pd.to_datetime(vz_df["period_end"]).isin(
        pd.to_datetime(["2013-12-31", "2014-12-31"])
    )
    & (vz_df["form_type"] == "10-K")
]

print(matches[[
    "period_end",
    "numeric_value",
    "unit",
    "filing_date",
    "accession"
]].sort_values(["filing_date", "period_end"]).to_string(index=False))

period_end  numeric_value unit filing_date            accession
2013-12-31    645000000.0  USD  2014-02-27 0001193125-14-073266
2013-12-31    645000000.0  USD  2015-02-23 0001193125-15-057710
2014-12-31    739000000.0  USD  2015-02-23 0001193125-15-057710
2014-12-31    739000000.0  USD  2016-02-23 0001193125-16-473367

In [ ]:
filing_id = "0001193125-15-057710"

pair = matches[
    (matches["accession"] == filing_id)
    & (matches["unit"] == "USD")
].copy()

pair["period_end"] = pd.to_datetime(pair["period_end"])
assert len(pair) == 2 and pair["period_end"].nunique() == 2

values = pair.set_index("period_end")["numeric_value"]
before = values.loc[pd.Timestamp("2013-12-31")]
after = values.loc[pd.Timestamp("2014-12-31")]

print("Change in USD:", after - before)
print("Supports 'increase':", after > before)

Change in USD: 94000000.0
Supports 'increase': False

### Mini test 1: Verizon allowance increased

- Triple ID: vz_2015_page_28_chunk_2_triplet_4
- Graph claim: Verizon's allowance for uncollectible accounts
  receivable increased during 2014.
- XBRL concept: us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent
- Accession: 0001193125-15-057710
- Unit: USD
- 2013-12-31: 645,000,000
- 2014-12-31: 739,000,000
- Change: +94,000,000
- Result: Direction supported, conditional on the concept mapping.
- Remaining checks: Confirm that the current-receivables concept
  matches the source table's scope and resolve the source-filing identity.